# Generated by Django 4.0 on 2022-01-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0014_delete_feedbacknews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliexpress',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
